---
# Run iNR on kubernetes
# Copied from https://wikitech.wikimedia.org/wiki/Help:Toolforge/Kubernetes#Kubernetes_continuous_jobs
# FIXME: Needs to be updated for 2020 k8s on Toolforge
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: inaturalistreviewer.bot
  namespace: inaturalistreviewer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: inaturalistreviewer.bot
    spec:
      containers:
        - name: bot
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          command: [ "/data/project/inaturalistreviewer/venv/bin/python3", "/data/project/inaturalistreviewer/iNaturalistReviewer/src/inrbot.py", "--auto" ]
          workingDir: /data/project/inaturalistreviewer
          env:
            - name: HOME
              value: /data/project/inaturalistreviewer
          imagePullPolicy: Always
          volumeMounts:
            - name: home
              mountPath: /data/project/inaturalistreviewer
      volumes:
        - name: home
          hostPath:
            path: /data/project/inaturalistreviewer
