name: Notify

on:
  issues:
      types: [labeled]

jobs:
  notify:

    runs-on: ubuntu-latest
    
    if: github.event.label.name == 'prod-error'

    steps:
    - name: Debug
      run: echo ${{github.event}}
    - name: Fail
      run: exit 1 
