name: Notify

on:
  issues:
      types: created

jobs:
  notify:

    runs-on: ubuntu-latest
    
    if: contains(github.event.issue.labels.*.name, 'prod-error')

    steps:
    - name: Debug
      run: echo ${{github.event}}
    - name: Fail
      run: exit 1 
